# Generated by Django 5.0.7 on 2024-09-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('publication_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
